---
- hosts: web 
  user: springboard
  tasks:
    # copy from build on host. we can't use relative path from here because 
    - copy: src=/vagrant/packer/springboard-wheezy-virtualbox-{{build_version}}.box dest=/var/www/boxes.springboard.spry-group.com/html/springboard-wheezy-{{build_version}}.vbox

